import { Home, Plane } from 'lucide-react';

import type {
  BudgetPreset,
  DocumentChecklistItem,
  DropdownOption,
  MissionVisaOption,
  RequestFormStep,
  ResidencyOption,
  TimelineShortcut,
} from '@/app/requests/new/types';
import { visaRequirements } from '@/config/visaRequirements';

export const visaTypeOptions: DropdownOption[] = [
  { value: 'NON-IMM-B', label: 'Non-Immigrant B (Business / Work)' },
  { value: 'NON-IMM-O', label: 'Non-Immigrant O (Marriage / Guardian)' },
  { value: 'NON-IMM-ED', label: 'Non-Immigrant ED (Education)' },
  { value: 'LTR', label: 'Long-Term Resident (LTR)' },
  { value: 'DTV', label: 'Digital Nomad (DTV)' },
  { value: 'VOLUNTEER', label: 'Volunteer Visa' },
  { value: 'RETIREMENT', label: 'Retirement Visa' },
  { value: 'OTHER', label: 'Other / Not Sure' },
];

export const locationOptions: DropdownOption[] = [
  { value: 'BANGKOK', label: 'Bangkok (BKK)' },
  { value: 'CHIANG_MAI', label: 'Chiang Mai' },
  { value: 'PHUKET', label: 'Phuket' },
  { value: 'PATTAYA', label: 'Pattaya / Chonburi' },
  { value: 'SAMUI', label: 'Koh Samui / Surat Thani' },
  { value: 'HUA_HIN', label: 'Hua Hin / Cha-Am' },
  { value: 'KRABI', label: 'Krabi / Phang Nga' },
  { value: 'ABROAD', label: 'Applying from outside Thailand' },
  { value: 'OTHER', label: 'Somewhere else' },
];

export const assistanceNeeds = [
  'Visa strategy & eligibility',
  'Document preparation',
  'Translations & certifications',
  'Appointment booking',
  'Immigration accompaniment',
  'Follow-up after submission',
];

export const documentChecklist: DocumentChecklistItem[] = [
  { key: 'passport', label: 'Passport (6+ months validity)' },
  { key: 'financial', label: 'Financial statements / proof of income' },
  { key: 'police', label: 'Police clearance' },
  { key: 'medical', label: 'Medical certificate' },
  { key: 'sponsor', label: 'Employment / sponsor letter' },
  { key: 'family', label: 'Marriage / birth certificates' },
];

export const nationalityOptions: DropdownOption[] = [
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Macau', label: 'Macau' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Moldova', label: 'Moldova' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'North Macedonia', label: 'North Macedonia' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russia', label: 'Russia' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Korea', label: 'South Korea' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'United States', label: 'United States' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
  { value: 'Other / Not listed', label: 'Other / Not listed' },
];

export const inThailandVisaOptions: DropdownOption[] = [
  { value: 'TOURIST', label: 'Tourist visa (TR)' },
  { value: 'NON-IMM-B', label: 'Non-Immigrant B (Work)' },
  { value: 'NON-IMM-O', label: 'Non-Immigrant O (Marriage/Guardian)' },
  { value: 'NON-IMM-ED', label: 'Non-Immigrant ED (Education)' },
  { value: 'RETIREMENT', label: 'Retirement visa' },
  { value: 'DTV', label: 'Digital nomad (DTV)' },
  { value: 'OTHER', label: 'Other / Not sure' },
];

export const ageRangeOptions: DropdownOption[] = [
  { value: '18-49', label: '18 - 49 years' },
  { value: '50+', label: '50+ years' },
];

export const residencyOptions: ResidencyOption[] = [
  {
    value: 'IN_THAILAND',
    label: 'I am currently in Thailand',
    description: 'Great for extensions or conversions',
    icon: Home,
  },
  {
    value: 'OUTSIDE_THAILAND',
    label: 'I am outside Thailand',
    description: 'Preparing before arriving',
    icon: Plane,
  },
];

export const budgetPresets: BudgetPreset[] = [
  { label: 'THB 5k - 10k', min: 5000, max: 10000, description: 'Straightforward extensions & tourist help' },
  { label: 'THB 10k - 20k', min: 10000, max: 20000, description: 'Most Non-Imm B / O conversions' },
  { label: 'THB 20k - 35k', min: 20000, max: 35000, description: 'LTR, families, and multi-step support' },
  { label: 'THB 35k+', min: 35000, max: 60000, description: 'Complex cases with concierge handling' },
];

export const missionVisaOptions: MissionVisaOption[] = [
  ...visaRequirements.map((requirement) => ({
    value: requirement.id,
    label: requirement.label,
    description: requirement.summary,
    badge: requirement.badge,
    details: requirement.highlights,
  })),
  {
    value: 'OTHER',
    label: 'Other / Not sure',
    description: 'Need help deciding.',
    details: ['Providers can recommend eligibility path', 'Share current situation to start'],
  },
];

export const featuredLocationOptions = ['BANGKOK', 'CHIANG_MAI', 'PHUKET', 'PATTAYA', 'SAMUI', 'HUA_HIN'];

export const timelineShortcuts: TimelineShortcut[] = [
  {
    label: 'Within 2 weeks',
    value: 'Need approval within 2 weeks',
    description: 'Emergency conversions or looming expirations',
  },
  {
    label: 'Within 1 month',
    value: 'Need approval within 1 month',
    description: 'Standard processing with some buffer',
  },
  {
    label: 'Within 3 months',
    value: 'Need approval within 3 months',
    description: 'Planning ahead for new relocations',
  },
];

export const formSteps: RequestFormStep[] = [
  {
    id: 'personal',
    title: 'About you',
    subtitle: 'Confirm age, nationality, and where you’re applying from.',
  },
  {
    id: 'mission',
    title: 'Your visa plan',
    subtitle: 'Pick your visa track and your preferred location.',
  },
  {
    id: 'budget',
    title: 'Budget & timing',
    subtitle: 'Set expectations so providers can respond accurately.',
  },
  {
    id: 'support',
    title: 'Support & documents',
    subtitle: 'Choose the touchpoints and document readiness.',
  },
];
